### ISSUE TITLE
ToMatrix() does not have backward operation implemented 

### ISSUE THREAD

**Issue by lixiny** [princeton-vl/lietorch#1]
Hi, 

I just read through your paper and code  and really adore this project on lie group in tangent space. 

I hope that the ToMatrix() operation could be fully differentiable for researchers to use. 
Do you have a plan to implement the *ToMatrix()*, or may be *FromMatrix()* in the future? and a planned date in mind? 

Cheers 

Lixin

**Comment by zachteed** [comment]
Hi Lixin, I agree this would be good to have. I do have equations for the gradients of `ToMatrix` so I can add this in the next few days. I will need to think about `FromMatrix`.

In the future, I am working on trying to make conversions from all different representations differentiable (e.g quaternions, matricies, ect).

Best,
Zach

**Comment by lixiny** [comment]
Best, Zach.
Thanks again for the great contribution you have made. 

Lixin
