### ISSUE TITLE
Question about the Euclidean embeddings 

### ISSUE THREAD

**Issue by xwjabc** [princeton-vl/lietorch#11]
Hi, thank you for your great work! Since I am new to the Lie groups and Lie algebra, I met some difficulties when reading the code:

1. For SE(3) representation, the Euclidean embeddings (that is, the 7-dim vector from `ToVec()` function) has two parts: 3-dim translation and 4-dim quaternion (for rotation) ([related code](https://github.com/princeton-vl/lietorch/blob/0fa9ce8ffca86d985eca9e189a99690d6f3d4df6/lietorch/include/se3.h#L41)). When I tried to create a pose from the axis-angle representation (i.e. `SE3.exp(axis_angle_rep)`), [this code](https://github.com/princeton-vl/lietorch/blob/0fa9ce8ffca86d985eca9e189a99690d6f3d4df6/lietorch/include/se3.h#L134) multiplies left Jacobian with `tau`, which should correspond to the translation from axis-angle representation:

   ```Vector3 t = SO3<Scalar>::left_jacobian(phi) * tau;```
   
   My question is, why should we multiply `tau` with left Jacobian of `phi`? Could you explain a little bit more on the connection between the Euclidean embeddings and axis-angle (or transformation matrix)? I found some [webpage](https://rock-learning.github.io/pytransform3d/transformations.html#logarithm-of-transformation) shows the connections among various representations but I think it still a bit unclear. Thanks!

**Comment by xwjabc** [comment]
Ah I found out the reason. The exponential function will apply to both tau and phi when converting to rotation matrix. The tau is not translation in the world coordinates.

**Comment by zachteed** [comment]
Hi, that's correct, the tau is in exponential coordinates, not world coordinates. If you take a look at this reference, https://ethaneade.com/lie_groups.pdf, what is being computing when calling SE3.exp is equal to the formula in section 9.4 (with the exception that I am using unit quaternions to represent rotation instead of matrices).

**Comment by xwjabc** [comment]
Hi Zach, thank you for your reply! This looks like a nice reference and I will carefully read it!
